/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudyIndiaRouteImport } from './routes/study-india'
import { Route as StudyEuropeRouteImport } from './routes/study-europe'
import { Route as StudyAbroadRouteImport } from './routes/study-abroad'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as MbbsAbroadRouteImport } from './routes/mbbs-abroad'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CareerCounselingRouteImport } from './routes/career-counseling'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const StudyIndiaRoute = StudyIndiaRouteImport.update({
  id: '/study-india',
  path: '/study-india',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyEuropeRoute = StudyEuropeRouteImport.update({
  id: '/study-europe',
  path: '/study-europe',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyAbroadRoute = StudyAbroadRouteImport.update({
  id: '/study-abroad',
  path: '/study-abroad',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const MbbsAbroadRoute = MbbsAbroadRouteImport.update({
  id: '/mbbs-abroad',
  path: '/mbbs-abroad',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerCounselingRoute = CareerCounselingRouteImport.update({
  id: '/career-counseling',
  path: '/career-counseling',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/career-counseling': typeof CareerCounselingRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/mbbs-abroad': typeof MbbsAbroadRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/study-abroad': typeof StudyAbroadRoute
  '/study-europe': typeof StudyEuropeRoute
  '/study-india': typeof StudyIndiaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/career-counseling': typeof CareerCounselingRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/mbbs-abroad': typeof MbbsAbroadRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/study-abroad': typeof StudyAbroadRoute
  '/study-europe': typeof StudyEuropeRoute
  '/study-india': typeof StudyIndiaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/career-counseling': typeof CareerCounselingRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/mbbs-abroad': typeof MbbsAbroadRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/study-abroad': typeof StudyAbroadRoute
  '/study-europe': typeof StudyEuropeRoute
  '/study-india': typeof StudyIndiaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/career-counseling'
    | '/contact'
    | '/events'
    | '/mbbs-abroad'
    | '/sitemap.xml'
    | '/study-abroad'
    | '/study-europe'
    | '/study-india'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/career-counseling'
    | '/contact'
    | '/events'
    | '/mbbs-abroad'
    | '/sitemap.xml'
    | '/study-abroad'
    | '/study-europe'
    | '/study-india'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/career-counseling'
    | '/contact'
    | '/events'
    | '/mbbs-abroad'
    | '/sitemap.xml'
    | '/study-abroad'
    | '/study-europe'
    | '/study-india'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CareerCounselingRoute: typeof CareerCounselingRoute
  ContactRoute: typeof ContactRoute
  EventsRoute: typeof EventsRoute
  MbbsAbroadRoute: typeof MbbsAbroadRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StudyAbroadRoute: typeof StudyAbroadRoute
  StudyEuropeRoute: typeof StudyEuropeRoute
  StudyIndiaRoute: typeof StudyIndiaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/study-india': {
      id: '/study-india'
      path: '/study-india'
      fullPath: '/study-india'
      preLoaderRoute: typeof StudyIndiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study-europe': {
      id: '/study-europe'
      path: '/study-europe'
      fullPath: '/study-europe'
      preLoaderRoute: typeof StudyEuropeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study-abroad': {
      id: '/study-abroad'
      path: '/study-abroad'
      fullPath: '/study-abroad'
      preLoaderRoute: typeof StudyAbroadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mbbs-abroad': {
      id: '/mbbs-abroad'
      path: '/mbbs-abroad'
      fullPath: '/mbbs-abroad'
      preLoaderRoute: typeof MbbsAbroadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career-counseling': {
      id: '/career-counseling'
      path: '/career-counseling'
      fullPath: '/career-counseling'
      preLoaderRoute: typeof CareerCounselingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CareerCounselingRoute: CareerCounselingRoute,
  ContactRoute: ContactRoute,
  EventsRoute: EventsRoute,
  MbbsAbroadRoute: MbbsAbroadRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StudyAbroadRoute: StudyAbroadRoute,
  StudyEuropeRoute: StudyEuropeRoute,
  StudyIndiaRoute: StudyIndiaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
